name: BlueMapSignMarkers
version: ${version}
main: dev.kugge.signmarkers.SignMarkers
api-version: 1.21.1
folia-supported: true
authors: [kugge]
depend: [BlueMap]
description: Add markers to BlueMap with signs